<?php require_once './templates/header.phtml'; ?>

    <div class="about">

        <h2>Presentación</h2>

        <p>Bienvenido a la Biblioteca de Obras Diversas,
            un recurso que se especializa en una amplia gama de categorías literarias,
            desde novelas y ensayos hasta poesía y ciencia.
            Nuestra colección abarca una variedad de géneros y temas para satisfacer la curiosidad y
            los intereses de nuestros usuarios.</p>

        <h2>Historia</h2>

        <p>La Biblioteca de Obras Diversas tiene una rica historia que se remonta a su fundación en
            2001. Desde entonces, hemos estado comprometidos en proporcionar acceso a la literatura
            en todas sus formas.
            Inicialmente, comenzamos como una modesta colección de libros en una pequeña sala,
            pero con el tiempo, hemos crecido y diversificado nuestra colección para abarcar todas
            las categorías literarias imaginables.</p>

        <h2>Misión y Visión</h2>

        <p>Nuestra misión es promover el amor por la lectura y el aprendizaje
            al brindar acceso a una amplia variedad de obras literarias.
            Buscamos ser una fuente de inspiración, conocimiento y entretenimiento para nuestra
            comunidad de usuarios, apoyando la educación y la exploración intelectual.</p>

        <p>Nuestra visión es fomentar la creatividad, el pensamiento crítico y el enriquecimiento
            cultural a través de nuestra colección diversa.
            Nos esforzamos por ser un centro de recursos literarios en el que las personas puedan
            descubrir nuevas perspectivas y expandir sus horizontes intelectuales.</p>

        <h2>Valores</h2>

        <ul>
            <li><strong>Diversidad Literaria:</strong>
                Creemos en la importancia de ofrecer una amplia gama de géneros y categorías literarias
                para satisfacer los gustos y necesidades de nuestros usuarios.</li>

            <li><strong>Accesibilidad:</strong>
                Nos comprometemos a proporcionar un acceso igualitario a la literatura para todos,
                sin importar su origen o situación.</li>

            <li><strong>Excelencia en el Servicio:</strong>
                Nuestro equipo está dedicado a brindar un servicio excepcional y orientación
                a nuestros usuarios.</li>

            <li><strong>Preservación Literaria:</strong>
                Valoramos la conservación y preservación de obras literarias valiosas
                para las generaciones futuras.</li>

            <li><strong>Comunidad Literaria:</strong>
                Fomentamos la creación de una comunidad de amantes de la literatura que puedan
                compartir su pasión y conocimientos.</li>
        </ul>

        <p>Esperamos que esta breve introducción te proporcione una visión clara de lo que representa
            la Biblioteca de Obras Diversas y cómo estamos comprometidos a servir a la comunidad literaria.
            Si tienes alguna pregunta o necesitas más información, no dudes en ponerte en contacto
            con nosotros.</p>
    </div>

<?php require_once './templates/footer.phtml'; ?>