<form action="agregarLibro/<?= $categorieId ?>" method="GET" class="form-categoria">
    <div>
        <label for="titulo">Titulo</label>
        <input class="form-control form-control-sm" name="titulo_libro" type="text" placeholder="Titulo">
        <br>
        <label for="autor">Autor</label>
        <input class="form-control form-control-sm" name="autor_libro" type="text" placeholder="Autor">
        <br>
        <label for="anio">Año</label>
        <input class="form-control form-control-sm" name="anio" type="text" placeholder="Año">
    </div>
    <button type="submit" class="btn btn-secondary">Agregar libro</button>
    <?php
    if (isset($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <?php endif; ?>
</form>