<form action="agregarLibro/<?= $categoriaId ?>" method="GET" class="form-categoria">
    <div>
        <label for="titulo">Titulo</label>
        <input class="form-control form-control-sm" name="titulo" type="text" placeholder="Titulo">

        <label for="autor">Autor</label>
        <input class="form-control form-control-sm" name="autor" type="text" placeholder="Autor">

        <label for="anio">Año</label>
        <input class="form-control form-control-sm" name="anio" type="text" placeholder="Año">
    </div>
    <button type="submit" class="btn btn-secondary">Agregar libro</button>
</form>