<?php require_once './templates/header.phtml';?>
<div class="login">
    <form action="procesar.php" method="POST">
        
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required><br><br>
        
        <label for="contrasena">Contraseña:</label>
        <input type="password" id="contrasena" name="contrasena" required><br><br>
        
        <input type="submit" value="Guardar">

    </form>
</div>

<?php require_once './templates/footer.phtml';?>