<?php require_once './templates/header.phtml';

$hrefId = '';

?>
<h4>Listado de libro por categoria: </h4>
<table class="table table-striped ">
    <thead>
        <tr>

            <th class="col-sm-4">Título</th>

            <th class="col-sm-4">Autor</th>

            <th class="col-sm-4">Año</th>
            <?php if ($rol === 1) {
            ?>
                <th class="col-sm-4">Acciones</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($listBooks as $book) {
            $hrefId = $book->id_libro;

        ?>
            <tr class="justify-content-evently">
                <td><?php echo $book->titulo_libro ?></td>
                <td><?php echo $book->autor_libro ?></td>
                <td><?php echo $book->anio ?></td>
                <?php if ($rol === 1) {
                ?>
                    <td class = "td-btn">
                        <a href="editarLibro/<?= $hrefId  ?>" type="button" class='btn btn-primary btn-sm btn-edit'>Editar</a>

                        <a href="eliminarLibro/<?= $categorieId ?>/<?= $book->id_libro ?>" type="button" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>

    </tbody>
</table>

<?php
if ($rol === 1) {
    require_once './templates/addBook.phtml';
}
?>

<?php require_once './templates/footer.phtml'; ?>