<?php require_once './templates/Header.phtml';

$href = '';
$rolUsuario = '';
?>
<table class="table col-6">
    <thead>
        <tr class="justify-content-evently">
            <th col-sm-4>Categoría</th>
            <th col-sm-4>Acciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($categorias as $categoria) {
            $href = $categoria->id_categoria;
        ?>
            <tr class="justify-content-between">
                <td>
                    <a href="libroByCategoria/<?php echo $href ?>"><?php echo $categoria->categoria ?></a>
                </td>
            
                <td <?php
                var_dump($rolUsuario);
                if($rolUsuario != 0) {
                    
                ?>>
                <?php
                var_dump($rolUsuario);?>
                    <a href="editCategoria/<?= $href  ?>" type="button" class='btn btn-primary btn-sm btn-edit'>Editar</a>

                    <a href="eliminarCategoria/<?= $href  ?>" type="button" class='btn btn-danger btn-sm'>Eliminar</a>
                </td <?php } ?>>
            </tr>
        <?php } ?>
    </tbody>
</table>
<?php require_once 'templates/FormCategoria.phtml' ?>
<?php require_once 'templates/Footer.phtml' ?>
