<?php require_once './templates/header.phtml'; ?>
<div class="login">
    <form action="registro" method="POST">

        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required><br><br>

        <label for="contrasena">Contraseña:</label>
        <input type="password" id="contrasenia" name="password" required><br><br>

        <input type="submit" value="Registrarme">

    </form>
</div>

<?php require_once './templates/footer.phtml'; ?>