<?php require_once './templates/header.phtml';
?>
<form action="actualizarLibro/<?= $idBook   ?>" method="POST" class="form-categoria">

    <div>
        <label for="editarLibro/<?= $id  ?>">Titulo</label>
        <input class="form-control form-control-sm" name="nuevoTitulo" type="text" placeholder="Titulo">

        <label for="editarLibro/<?= $id  ?>">Autor</label>
        <input class="form-control form-control-sm" name="nuevoAutor" type="text" placeholder="Autor">

        <label for="editarLibro/<?= $id  ?>">Año</label>
        <input class="form-control form-control-sm" name="nuevoAnio" type="text" placeholder="Año">
    </div>
    <?php if (isset($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <?php endif; ?>
    <button type="submit" class="btn btn-secondary">Actualizar titulo</button>
</form>


<?php require_once './templates/footer.phtml'; ?>