<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <base href="<?php echo BASE_URL ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="stylesheet" href="css/Style.css">
  <title>Biblioteca</title>
</head>


<body>
  <header>
    <?php if ($error) : ?>
      <div class='alert alert-danger' role='alert'>
        <?= $error ?>
      </div>
    <?php endif ?>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="home">BIBLIOTECA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="home">Home</a>
            </li>
            <li class="nav-item dropdown">
              <?php if (!isset($_SESSION['USER_NAME'])) : ?>

              <?php else : ?>
                <a class="nav-link dropdown-toggle" href="categorias" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Libros
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="categorias">Categorias</a></li>
                </ul>
              <?php endif; ?>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="about">Abouts</a>
            </li>
            <?php if (!isset($_SESSION['USER_NAME'])) : ?>
              <li class="nav-item " >
                <a class="nav-link" href="login">Login</a>
              </li>
            <?php else : ?>
              <li class="nav-item">
                <a class="nav-link logout" aria-current="page" href="logOut">LogOut (<?= $_SESSION['USER_NAME'] ?>)</a>
              </li>
            <?php endif ?>
          </ul>
        </div>
          
      </div>
    </nav>
  </header>