<?php require_once './templates/Header.phtml'; ?>

<div class="login">         
    
    <form method="POST" action="auth">
        
        <div>
            <label>Usuario</label>
            <input type="text" name="usuario" placeholder="Ingresar Usuario">
        </div>
        
        <div>
            <label>Password</label>
            <input type="password" name="password" placeholder="Password">
        </div>
        
        <div>
            <div class="uno">
            <input type="checkbox">
            <label> Remember me </label>
        </div>
    
    </form>     
        
        <div class="dos">
            <button  type="submit">Sign in</button>
            <a href="singup">Sign up</a>
            <a href="#">Forgot password?</a>
        </div>   
</div>              

<?php require_once './templates/Footer.phtml'; ?>